### ISSUE TITLE
Use Valid jquery-browser Version

### ISSUE THREAD

**Issue by Nicholas-Westby** [rhythmagency/rhythm.toolkit#1]
https://github.com/rhythmagency/rhythm.toolkit/blob/8204a7d39678434d11b1770ddd43bd5e24cd620a/templates/frontend/package.json

jquery-browser is specified. Now, when people try to do "npm install" on projects that use rhythm.toolkit, they seem to get an error saying the jquery-browser version is invalid. Perhaps change the version to one that is allowed (my guess is a version go removed).

**Comment by michael-lawrence** [comment]
Check https://github.com/kapouer/jquery-browser . It says the package is deprecated and to use "jquery" instead. Probably should update all references to jquery-browser and point them to jquery and test.

**Comment by Nicholas-Westby** [comment]
Oops, this issue should have been created on rhythm.framework rather than rhythm.toolkit. May also apply here, but I'm closing this issue, as this project has been superseded by generator-rhythm.
